iface: 'ens33'
nginx_port: 80
nginx_log_dir: "/var/log/nginx"
nginx_documentroot: "/usr/share/nginx/html"
serverspec_base_dir: "/usr/local/serverspec"
serverspec_exec_user_name: "jenkins"
serverspec_exec_user_group: "jenkins"
elasticsearch_host: "kibana.devops-book.local"
elasticsearch_port: 9200
